# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='custom_id',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
